"""add order reservation fields

Revision ID: 080ad7c02487
Revises: 04db6c3f1a82
Create Date: 2026-07-27 16:28:07.296012

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "080ad7c02487"
down_revision: str | Sequence[str] | None = "04db6c3f1a82"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders", sa.Column("product_id", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "orders",
        sa.Column("reservation_expires_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "orders",
        sa.Column(
            "stock_reserved",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.create_foreign_key(None, "orders", "products", ["product_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_column("orders", "stock_reserved")
    op.drop_column("orders", "reservation_expires_at")
    op.drop_column("orders", "product_id")
    # ### end Alembic commands ###
