"""add products table

Revision ID: 3fe6073f23d2
Revises: 1883267f26fc
Create Date: 2026-07-15 13:41:42.943940

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3fe6073f23d2"
down_revision: str | Sequence[str] | None = "1883267f26fc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("quantity_in_stock", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    products_table = sa.table(
        "products",
        sa.Column("id", sa.String),
        sa.Column("name", sa.String),
        sa.Column("price", sa.Integer),
        sa.Column("currency", sa.String),
        sa.Column("description", sa.String),
        sa.Column("quantity_in_stock", sa.Integer),
    )

    op.bulk_insert(
        products_table,
        [
            {
                "id": "speaker",
                "name": "Portable Speaker",
                "price": 4999,
                "currency": "USD",
                "description": (
                    "A waterproof Bluetooth speaker with up to "
                    "10 hours of battery life."
                ),
                "quantity_in_stock": 10,
            },
            {
                "id": "laptop",
                "name": "15.6 inch Business Laptop",
                "price": 29999,
                "currency": "USD",
                "description": (
                    "A business laptop with a 15.6 inch screen, "
                    "Intel Core i7 processor, 16GB of RAM, and a 512GB SSD."
                ),
                "quantity_in_stock": 8,
            },
            {
                "id": "camera",
                "name": "Full-Frame Mirrorless Camera",
                "price": 34999,
                "currency": "USD",
                "description": (
                    "A 33MP full-frame mirrorless camera, capable of up to "
                    "4K 60p in all recording formats."
                ),
                "quantity_in_stock": 4,
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("products")
    # ### end Alembic commands ###
