"""add orders query indexes

Revision ID: 582ee2596a47
Revises: 4126551f6728
Create Date: 2026-07-30 09:52:27.779335

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "582ee2596a47"
down_revision: str | Sequence[str] | None = "4126551f6728"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_orders_created_at_id", "orders", ["created_at", "id"], unique=False
    )
    op.create_index(
        "ix_orders_fulfillment_status", "orders", ["fulfillment_status"], unique=False
    )
    op.create_index("ix_orders_product_id", "orders", ["product_id"], unique=False)
    op.create_index("ix_orders_status", "orders", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_orders_status", table_name="orders")
    op.drop_index("ix_orders_product_id", table_name="orders")
    op.drop_index("ix_orders_fulfillment_status", table_name="orders")
    op.drop_index("ix_orders_created_at_id", table_name="orders")
    # ### end Alembic commands ###
