"""add processed qstash messages

Revision ID: d996af08905f
Revises: 582ee2596a47
Create Date: 2026-08-03 14:46:15.460703

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d996af08905f"
down_revision: str | Sequence[str] | None = "582ee2596a47"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processed_qstash_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("jti", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_processed_qstash_messages_jti"),
        "processed_qstash_messages",
        ["jti"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_processed_qstash_messages_jti"), table_name="processed_qstash_messages"
    )
    op.drop_table("processed_qstash_messages")
    # ### end Alembic commands ###
